# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
articles = Article.create([
    {
      title: "Lorem ipsum dolor sit amet",
      text: "Aliquam nec ante sit amet eros convallis iaculis non vitae neque. Etiam fringilla, felis a posuere molestie, urna ligula maximus neque, nec hendrerit lectus libero pulvinar eros. Etiam congue faucibus lectus, at laoreet mi pulvinar ac. Phasellus malesuada nec tellus non molestie. Etiam tempor urna velit, quis consectetur nulla bibendum ut. Nulla vestibulum augue eros, blandit auctor ante venenatis at. Praesent nec scelerisque ipsum, eget sollicitudin ligula. Quisque non lectus diam. Nam lobortis magna sed nulla finibus placerat. Etiam auctor ligula lacus, eget aliquet tortor faucibus id
      Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Praesent rhoncus, quam a sodales lobortis, dui elit accumsan ipsum, eu laoreet massa mauris id orci. Suspendisse potenti. Etiam feugiat semper pharetra. Vivamus rhoncus ipsum arcu, id tempor mauris fermentum ac. Morbi sed varius velit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc a molestie lectus. Suspendisse arcu tellus, interdum sit amet metus a, consequat lobortis nibh. Etiam sed felis pellentesque, feugiat est eu, tempor lectus. Cras nulla dui, pulvinar sed nulla a, imperdiet tempus erat. Aenean ullamcorper turpis quis maximus posuere. Ut eu tellus sollicitudin, mattis nunc vitae, efficitur enim. Nulla cursus dui vitae lorem maximus, quis accumsan arcu ornare. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Etiam libero justo, hendrerit vitae sem id, malesuada consequat ante
      Mauris nunc ligula, convallis a ligula vel, fermentum vestibulum lectus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Curabitur ac nunc vulputate, molestie leo eu, tempus tortor. Fusce sed vulputate ante. Quisque condimentum massa et ante vehicula, a fermentum sapien fringilla. Aliquam porttitor varius arcu et rhoncus. Proin pharetra tortor in consectetur ultrices. Curabitur feugiat facilisis congue. Suspendisse euismod magna enim, sit amet mattis risus volutpat vitae. Donec viverra ac erat sed elementum. Cras egestas auctor nisl, nec rutrum diam tincidunt sed
      Proin quis interdum metus. Donec eros nibh, lobortis a lectus at, euismod mollis sem. Praesent vel lacinia dolor. Proin pellentesque velit et arcu mattis molestie. Duis maximus urna quis sapien bibendum luctus id id ante. Duis vel vestibulum dui, sed feugiat enim. Mauris dui ex, varius quis facilisis nec, finibus non massa. Mauris magna dui, vestibulum eu tortor sed, pellentesque efficitur elit. Duis et dui mollis, aliquam felis non, sagittis ipsum. Sed quis massa nec dui sodales pellentesque non eget justo. Curabitur venenatis elit vitae ultrices volutpat. Nam et neque tellus. Aliquam erat volutpat
      Praesent id malesuada lectus, ac pharetra ligula. Sed feugiat nulla nec congue tempus. Nunc quis dictum leo. Etiam eget malesuada leo, vel porta quam. Vestibulum tristique congue ante nec sollicitudin. In vel eros augue. Phasellus ultricies, elit nec blandit placerat, magna leo dapibus nunc, in vulputate sapien ante eu lacus. Maecenas id egestas ante, ac varius tortor. Curabitur egestas lectus ut quam sagittis hendrerit. Praesent ullamcorper, tortor in egestas iaculis, turpis erat consectetur risus, vitae efficitur tellus dui et ante."
    },
    {
      title: "Lorem ipsum dolor sit amet 2",
      text: "Aliquam nec ante sit amet eros convallis iaculis non vitae neque. Etiam fringilla, felis a posuere molestie, urna ligula maximus neque, nec hendrerit lectus libero pulvinar eros. Etiam congue faucibus lectus, at laoreet mi pulvinar ac. Phasellus malesuada nec tellus non molestie. Etiam tempor urna velit, quis consectetur nulla bibendum ut. Nulla vestibulum augue eros, blandit auctor ante venenatis at. Praesent nec scelerisque ipsum, eget sollicitudin ligula. Quisque non lectus diam. Nam lobortis magna sed nulla finibus placerat. Etiam auctor ligula lacus, eget aliquet tortor faucibus id
      Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Praesent rhoncus, quam a sodales lobortis, dui elit accumsan ipsum, eu laoreet massa mauris id orci. Suspendisse potenti. Etiam feugiat semper pharetra. Vivamus rhoncus ipsum arcu, id tempor mauris fermentum ac. Morbi sed varius velit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc a molestie lectus. Suspendisse arcu tellus, interdum sit amet metus a, consequat lobortis nibh. Etiam sed felis pellentesque, feugiat est eu, tempor lectus. Cras nulla dui, pulvinar sed nulla a, imperdiet tempus erat. Aenean ullamcorper turpis quis maximus posuere. Ut eu tellus sollicitudin, mattis nunc vitae, efficitur enim. Nulla cursus dui vitae lorem maximus, quis accumsan arcu ornare. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Etiam libero justo, hendrerit vitae sem id, malesuada consequat ante
      Mauris nunc ligula, convallis a ligula vel, fermentum vestibulum lectus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Curabitur ac nunc vulputate, molestie leo eu, tempus tortor. Fusce sed vulputate ante. Quisque condimentum massa et ante vehicula, a fermentum sapien fringilla. Aliquam porttitor varius arcu et rhoncus. Proin pharetra tortor in consectetur ultrices. Curabitur feugiat facilisis congue. Suspendisse euismod magna enim, sit amet mattis risus volutpat vitae. Donec viverra ac erat sed elementum. Cras egestas auctor nisl, nec rutrum diam tincidunt sed
      Proin quis interdum metus. Donec eros nibh, lobortis a lectus at, euismod mollis sem. Praesent vel lacinia dolor. Proin pellentesque velit et arcu mattis molestie. Duis maximus urna quis sapien bibendum luctus id id ante. Duis vel vestibulum dui, sed feugiat enim. Mauris dui ex, varius quis facilisis nec, finibus non massa. Mauris magna dui, vestibulum eu tortor sed, pellentesque efficitur elit. Duis et dui mollis, aliquam felis non, sagittis ipsum. Sed quis massa nec dui sodales pellentesque non eget justo. Curabitur venenatis elit vitae ultrices volutpat. Nam et neque tellus. Aliquam erat volutpat
      Praesent id malesuada lectus, ac pharetra ligula. Sed feugiat nulla nec congue tempus. Nunc quis dictum leo. Etiam eget malesuada leo, vel porta quam. Vestibulum tristique congue ante nec sollicitudin. In vel eros augue. Phasellus ultricies, elit nec blandit placerat, magna leo dapibus nunc, in vulputate sapien ante eu lacus. Maecenas id egestas ante, ac varius tortor. Curabitur egestas lectus ut quam sagittis hendrerit. Praesent ullamcorper, tortor in egestas iaculis, turpis erat consectetur risus, vitae efficitur tellus dui et ante."
    },
    {
      title: "Lorem ipsum dolor sit amet 3",
      text: "Aliquam nec ante sit amet eros convallis iaculis non vitae neque. Etiam fringilla, felis a posuere molestie, urna ligula maximus neque, nec hendrerit lectus libero pulvinar eros. Etiam congue faucibus lectus, at laoreet mi pulvinar ac. Phasellus malesuada nec tellus non molestie. Etiam tempor urna velit, quis consectetur nulla bibendum ut. Nulla vestibulum augue eros, blandit auctor ante venenatis at. Praesent nec scelerisque ipsum, eget sollicitudin ligula. Quisque non lectus diam. Nam lobortis magna sed nulla finibus placerat. Etiam auctor ligula lacus, eget aliquet tortor faucibus id
      Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Praesent rhoncus, quam a sodales lobortis, dui elit accumsan ipsum, eu laoreet massa mauris id orci. Suspendisse potenti. Etiam feugiat semper pharetra. Vivamus rhoncus ipsum arcu, id tempor mauris fermentum ac. Morbi sed varius velit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc a molestie lectus. Suspendisse arcu tellus, interdum sit amet metus a, consequat lobortis nibh. Etiam sed felis pellentesque, feugiat est eu, tempor lectus. Cras nulla dui, pulvinar sed nulla a, imperdiet tempus erat. Aenean ullamcorper turpis quis maximus posuere. Ut eu tellus sollicitudin, mattis nunc vitae, efficitur enim. Nulla cursus dui vitae lorem maximus, quis accumsan arcu ornare. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Etiam libero justo, hendrerit vitae sem id, malesuada consequat ante
      Mauris nunc ligula, convallis a ligula vel, fermentum vestibulum lectus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Curabitur ac nunc vulputate, molestie leo eu, tempus tortor. Fusce sed vulputate ante. Quisque condimentum massa et ante vehicula, a fermentum sapien fringilla. Aliquam porttitor varius arcu et rhoncus. Proin pharetra tortor in consectetur ultrices. Curabitur feugiat facilisis congue. Suspendisse euismod magna enim, sit amet mattis risus volutpat vitae. Donec viverra ac erat sed elementum. Cras egestas auctor nisl, nec rutrum diam tincidunt sed
      Proin quis interdum metus. Donec eros nibh, lobortis a lectus at, euismod mollis sem. Praesent vel lacinia dolor. Proin pellentesque velit et arcu mattis molestie. Duis maximus urna quis sapien bibendum luctus id id ante. Duis vel vestibulum dui, sed feugiat enim. Mauris dui ex, varius quis facilisis nec, finibus non massa. Mauris magna dui, vestibulum eu tortor sed, pellentesque efficitur elit. Duis et dui mollis, aliquam felis non, sagittis ipsum. Sed quis massa nec dui sodales pellentesque non eget justo. Curabitur venenatis elit vitae ultrices volutpat. Nam et neque tellus. Aliquam erat volutpat
      Praesent id malesuada lectus, ac pharetra ligula. Sed feugiat nulla nec congue tempus. Nunc quis dictum leo. Etiam eget malesuada leo, vel porta quam. Vestibulum tristique congue ante nec sollicitudin. In vel eros augue. Phasellus ultricies, elit nec blandit placerat, magna leo dapibus nunc, in vulputate sapien ante eu lacus. Maecenas id egestas ante, ac varius tortor. Curabitur egestas lectus ut quam sagittis hendrerit. Praesent ullamcorper, tortor in egestas iaculis, turpis erat consectetur risus, vitae efficitur tellus dui et ante."
    },
    {
      title: "Lorem ipsum dolor sit amet 4",
      text: "Aliquam nec ante sit amet eros convallis iaculis non vitae neque. Etiam fringilla, felis a posuere molestie, urna ligula maximus neque, nec hendrerit lectus libero pulvinar eros. Etiam congue faucibus lectus, at laoreet mi pulvinar ac. Phasellus malesuada nec tellus non molestie. Etiam tempor urna velit, quis consectetur nulla bibendum ut. Nulla vestibulum augue eros, blandit auctor ante venenatis at. Praesent nec scelerisque ipsum, eget sollicitudin ligula. Quisque non lectus diam. Nam lobortis magna sed nulla finibus placerat. Etiam auctor ligula lacus, eget aliquet tortor faucibus id
      Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Praesent rhoncus, quam a sodales lobortis, dui elit accumsan ipsum, eu laoreet massa mauris id orci. Suspendisse potenti. Etiam feugiat semper pharetra. Vivamus rhoncus ipsum arcu, id tempor mauris fermentum ac. Morbi sed varius velit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc a molestie lectus. Suspendisse arcu tellus, interdum sit amet metus a, consequat lobortis nibh. Etiam sed felis pellentesque, feugiat est eu, tempor lectus. Cras nulla dui, pulvinar sed nulla a, imperdiet tempus erat. Aenean ullamcorper turpis quis maximus posuere. Ut eu tellus sollicitudin, mattis nunc vitae, efficitur enim. Nulla cursus dui vitae lorem maximus, quis accumsan arcu ornare. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Etiam libero justo, hendrerit vitae sem id, malesuada consequat ante
      Mauris nunc ligula, convallis a ligula vel, fermentum vestibulum lectus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Curabitur ac nunc vulputate, molestie leo eu, tempus tortor. Fusce sed vulputate ante. Quisque condimentum massa et ante vehicula, a fermentum sapien fringilla. Aliquam porttitor varius arcu et rhoncus. Proin pharetra tortor in consectetur ultrices. Curabitur feugiat facilisis congue. Suspendisse euismod magna enim, sit amet mattis risus volutpat vitae. Donec viverra ac erat sed elementum. Cras egestas auctor nisl, nec rutrum diam tincidunt sed
      Proin quis interdum metus. Donec eros nibh, lobortis a lectus at, euismod mollis sem. Praesent vel lacinia dolor. Proin pellentesque velit et arcu mattis molestie. Duis maximus urna quis sapien bibendum luctus id id ante. Duis vel vestibulum dui, sed feugiat enim. Mauris dui ex, varius quis facilisis nec, finibus non massa. Mauris magna dui, vestibulum eu tortor sed, pellentesque efficitur elit. Duis et dui mollis, aliquam felis non, sagittis ipsum. Sed quis massa nec dui sodales pellentesque non eget justo. Curabitur venenatis elit vitae ultrices volutpat. Nam et neque tellus. Aliquam erat volutpat
      Praesent id malesuada lectus, ac pharetra ligula. Sed feugiat nulla nec congue tempus. Nunc quis dictum leo. Etiam eget malesuada leo, vel porta quam. Vestibulum tristique congue ante nec sollicitudin. In vel eros augue. Phasellus ultricies, elit nec blandit placerat, magna leo dapibus nunc, in vulputate sapien ante eu lacus. Maecenas id egestas ante, ac varius tortor. Curabitur egestas lectus ut quam sagittis hendrerit. Praesent ullamcorper, tortor in egestas iaculis, turpis erat consectetur risus, vitae efficitur tellus dui et ante."
    }
  ])
